Feature: As a user of ITSM I want to be able to raise a service request to Create or Modify existing Change Management templates.

  @Sprint15-RI469-RI470-RI471-Test1
  Scenario Outline: Request a new Change Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition1 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition1 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass  | NormalClassType | ChangeReason   | ImpactOfFailure        | Urgency    | RiskLevel      | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CIToRelateToTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo                  | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Normal Class | Advanced Notice | Project Parent | 1-Extensive/Widespread | 1-Critical | 1-Minimum Risk | yes              | Affecting more than 50% | Add    | test1    | test2    | test3    | testprod    | yes                | CI1                  | TELEFONICA UK   | testco-ordgroup | Change Management - IT - Billing & Charging | onlytosupportteam | yes                      | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test2
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition2 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition2 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass  | NormalClassType | ChangeReason   | ImpactOfFailure        | Urgency    | RiskLevel      | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo                 | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Normal Class | BAU             | Project Parent | 1-Extensive/Widespread | 1-Critical | 1-Minimum Risk | yes              | Affecting more than 50% | Add    | test1    | test2    | test3    | testprod    | no                 | TELEFONICA UK   | testco-ordgroup | Change Management - IT - Internal Services | onlytosupportteam | no                       | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test3
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition3 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition3 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass  | NormalClassType     | ChangeReason  | ImpactOfFailure        | Urgency    | RiskLevel  | ServiceImpacting | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CIToRelateToTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo                    | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Normal Class | Permitted Exception | Project Child | 1-Extensive/Widespread | 1-Critical | 2-Low Risk | no               | Add    | test1    | test2    | test3    | testprod    | yes                | CI1                  | TELEFONICA UK   | testco-ordgroup | Change Management - IT - Online & Integration | onlytosupportteam | yes                      | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test4
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition4 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition4 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass  | NormalClassType     | ChangeReason  | ImpactOfFailure     | Urgency | RiskLevel  | ServiceImpacting | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo                 | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Normal Class | Permitted Exception | Project Child | 2-Significant/Large | 2-High  | 2-Low Risk | no               | Add    | test1    | test2    | test3    | testprod    | no                 | TELEFONICA UK   | testco-ordgroup | Change Management - IT - Operations (ITCC) | onlytosupportteam | no                       | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test5
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition5 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<PreApprovedClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition1 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass        | PreApprovedClassType | ChangeReason | ImpactOfFailure     | Urgency | RiskLevel  | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CIToRelateToTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo                        | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Pre-Approved Class | Impact               | Maintenance  | 2-Significant/Large | 2-High  | 2-Low Risk | yes              | Affecting more than 50% | Modify | test1    | test2    | test3    | testprod    | yes                | CI1                  | TELEFONICA UK   | testco-ordgroup | Change Management - IT - Retail, Sales & Services | onlytosupportteam | yes                      | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test6
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition6 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<PreApprovedClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition2 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass        | PreApprovedClassType | ChangeReason | ImpactOfFailure     | Urgency | RiskLevel     | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo    | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Pre-Approved Class | Impact               | Maintenance  | 2-Significant/Large | 2-High  | 3-Medium Risk | yes              | Affecting more than 50% | Modify | test1    | test2    | test3    | testprod    | no                 | TELEFONICA UK   | testco-ordgroup | Change Management - NW - Data | onlytosupportteam | no                       | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test7
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition7 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<PreApprovedClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition3 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass        | PreApprovedClassType | ChangeReason | ImpactOfFailure    | Urgency  | RiskLevel     | ServiceImpacting | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CIToRelateToTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo         | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Pre-Approved Class | No Impact            | Maintenance  | 3-Moderate/Limited | 3-Medium | 3-Medium Risk | no               | Modify | test1    | test2    | test3    | testprod    | yes                | CI1                  | TELEFONICA UK   | testco-ordgroup | Change Management - NW - Messaging | onlytosupportteam | yes                      | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test8
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition8 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<PreApprovedClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition4 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass        | PreApprovedClassType | ChangeReason     | ImpactOfFailure    | Urgency  | RiskLevel     | ServiceImpacting | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo        | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Pre-Approved Class | No Impact            | Solving Incident | 3-Moderate/Limited | 3-Medium | 3-Medium Risk | no               | Modify | test1    | test2    | test3    | testprod    | no                 | TELEFONICA UK   | testco-ordgroup | Change Management - NW - Property | onlytosupportteam | no                       | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test9
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition9 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition1 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass     | EmergencyClassType | ChangeReason     | ImpactOfFailure    | Urgency  | RiskLevel   | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CIToRelateToTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo     | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Emergency Class | Incident           | Solving Incident | 3-Moderate/Limited | 3-Medium | 4-High Risk | yes              | Affecting more than 50% | Remove | test1    | test2    | test3    | testprod    | yes                | CI1                  | TELEFONICA UK   | testco-ordgroup | Change Management - NW - Radio | onlytosupportteam | yes                      | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test10
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition10 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition2 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass     | EmergencyClassType | ChangeReason     | ImpactOfFailure   | Urgency | RiskLevel   | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo         | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Emergency Class | Incident           | Solving Incident | 4-Minor/Localized | 4-Low   | 4-High Risk | yes              | Affecting more than 50% | Remove | test1    | test2    | test3    | testprod    | no                 | TELEFONICA UK   | testco-ordgroup | Change Management - NW - Transport | onlytosupportteam | no                       | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test11
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition11 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition3 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass     | EmergencyClassType | ChangeReason               | ImpactOfFailure   | Urgency | RiskLevel    | ServiceImpacting | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CIToRelateToTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo     | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Emergency Class | Problem            | Fulfilling Service Request | 4-Minor/Localized | 4-Low   | 5-Major Risk | no               | Remove | test1    | test2    | test3    | testprod    | yes                | CI1                  | TELEFONICA UK   | testco-ordgroup | Change Management - NW - Voice | onlytosupportteam | yes                      | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test12
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition12 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition4 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<EmergencyClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass     | EmergencyClassType | ChangeReason               | ImpactOfFailure   | Urgency | RiskLevel    | ServiceImpacting | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo                            | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Emergency Class | Problem            | Fulfilling Service Request | 4-Minor/Localized | 4-Low   | 5-Major Risk | no               | Remove | test1    | test2    | test3    | testprod    | no                 | TELEFONICA UK   | testco-ordgroup | Change Management - SM - Telephony and Capita Systems | onlytosupportteam | no                       | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test13
  Scenario Outline: Request a new Change Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition1 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition1 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CIToRelateToTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass  | NormalClassType | ChangeReason   | ImpactOfFailure        | Urgency    | RiskLevel      | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CIToRelateToTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo           | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Normal Class | Advanced Notice | Project Parent | 1-Extensive/Widespread | 1-Critical | 1-Minimum Risk | yes              | Affecting more than 50% | Add    | test1    | test2    | test3    | testprod    | yes                | CI1                  | TELEFONICA UK   | testco-ordgroup | Change Management - SM - TuGo, Media | onlytosupportteam | yes                      | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test14
  Scenario Outline: Request a new Chanage Template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to create a new change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for test condition2 "<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Create New Change Template condition2 "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<SuccessfulCRQs>","<FrequencyOfUse>","<TemplateName>","<TemplateOwner>","<TemplateSummary>","<TemplateNotes>","<ChangeClass>","<NormalClassType>","<ChangeReason>","<ImpactOfFailure>","<Urgency>","<RiskLevel>","<ServiceImpacting>","<EffectOnService>","<OptCat>","<ProdCat1>","<ProdCat2>","<ProdCat3>","<ProductName>","<CIFixedForTemplate>","<CoOrdSupportOrg>","<CoOrdSupportGrp>","<ChgMgmtGrpTemplateRelateTo>","<TemplateVisibilty>","<TaskTemplateToBeAssigned>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                  | SuccessfulCRQs  | FrequencyOfUse | TemplateName | TemplateOwner | TemplateSummary                   | TemplateNotes | ChangeClass  | NormalClassType | ChangeReason   | ImpactOfFailure        | Urgency    | RiskLevel      | ServiceImpacting | EffectOnService         | OptCat | ProdCat1 | ProdCat2 | ProdCat3 | ProductName | CIFixedForTemplate | CoOrdSupportOrg | CoOrdSupportGrp | ChgMgmtGrpTemplateRelateTo | TemplateVisibilty | TaskTemplateToBeAssigned | WOSummary                  | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Create a new change template | CRQ000000249763 | VeryFrequent   | TestTemplate | Pam           | Test-Create a new change template | testnotes     | Normal Class | BAU             | Project Parent | 1-Extensive/Widespread | 1-Critical | 1-Minimum Risk | yes              | Affecting more than 50% | Add    | test1    | test2    | test3    | testprod    | no                 | TELEFONICA UK   | testco-ordgroup | Change Management - SMIP   | onlytosupportteam | no                       | Create new Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Add           | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test15
  Scenario Outline: Request to Modify an existing change template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to Modify an existing change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details to modify "<TemplateName>","<WhatToModify>","<ChgMgmtGrpTemplateRelateTo>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Modify an existing Change Template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<TemplateName>","<WhatToModify>","<ChgMgmtGrpTemplateRelateTo>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType                        | TemplateName | WhatToModify            | ChgMgmtGrpTemplateRelateTo                  | WOSummary                       | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Modify an existing change template | TestTemplate | Modify template details | Change Management - IT - Billing & Charging | Modify Existing Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Modify        | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |

  @Sprint15-RI469-RI470-RI471-Test16
  Scenario Outline: Request to remove a change template
    Given I navigate to Change Template Request Form "<Username>","<Password>"
    And I am requesting to remove a change template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>"
    When I enter the template details for removal "<TemplateName>","<JustificationForRemoval>","<ChgMgmtGrpTemplateRelateTo>"
    And submit the Change Template service request form
    Then the system will create a Work Order to Change Management "<WOSummary>","<WOPriority>","<WOSupportGroupName>","<WOCompany>","<WOOptCatTier1>","<WOOptCatTier2>","<WOOptCatTier3>","<WOProdCatTier1>","<WOProdCatTier2>","<WOProdCatTier3>","<WOProductName>"
    And the Work Order Notes field will contain all the details provided in the Service Request for Remove an existing Change Template "<LANID>","<OUC>","<Email>","<ContactNumber>","<ManagerName>","<RequestType>","<TemplateName>","<JustificationForRemoval>","<ChgMgmtGrpTemplateRelateTo>"

    Examples: 
      | Username | Password | LANID    | OUC | Email                          | ContactNumber | ManagerName | RequestType              | TemplateName | JustificationForRemoval | ChgMgmtGrpTemplateRelateTo                  | WOSummary              | WOPriority | WOSupportGroupName                          | WOCompany     | WOOptCatTier1 | WOOptCatTier2 | WOOptCatTier3   | WOProdCatTier1 | WOProdCatTier2 | WOProdCatTier3 | WOProductName   |
      | snarasi1 | test     | snarasi1 | TBC | Sharmendiran.Narasimhan@O2.COM |   07720869911 | Ummer       | Remove a change template | TestTemplate | Remove template details | Change Management - IT - Billing & Charging | Remove Change Template | Low        | Change Management - IT - Billing & Charging | TELEFONICA UK | Remove        | Data          | Change Template | Application    | COTS/Bespoke   | Software       | BMC Remedy ITSM |
